### ISSUE TITLE
cannot convert type: types.Decimal, MySQL/MariaDB

### ISSUE THREAD

**Issue by BenKnigge** [volatiletech/strmangle#12]
I see that this error has been marked as resolved, however I'm still seeing the issue.

Can't insert decimal into MySQL/MariaDB

Error :  cannot convert type: types.Decimal

MariaDB version : MariaDB 10.11

MySQL Decimal Type defined as : decimal(26,12)

Reverent modules
 
github.com/go-sql-driver/mysql v1.8.0
github.com/volatiletech/sqlboiler/v4 v4.16.2

**Comment by stephenafamo** [comment]
This issue is unrelated to this repository. Kindly open any issues in the relevant repositories.
